# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6RopflX8F_k4rphGVVUiOBEE58U_mF7
"""

import pickle

with open("model.pkl", "rb") as f:
    loaded_model = pickle.load(f)

y_pred = loaded_model.predict(X_test)